---
title: "R Notebook Sandbox"
author: "Christopher Mims"
date: "'r format(Sys.time(), '%d %B %Y')'"
output:
    pdf_document:
      citation_package: natbib
      latex_engine: pdflatex
      template: ./../latex-templates/homework.tex
      fig_caption: true
      number_sections: true
    html_document:
      df_print: paged
course: "STATS 419 Survey of Multivariate Analysis"
course-short: STATS419
instructor: Monte J. Shaffer
email: "chirs24m@wsu.edu"
---


```{r,mychunk-1,message=FALSE}
library(devtools); # devtools is required for function source_url() to work
my.source = 'github';
github.path = "https://raw.githubusercontent.com/DataChris24/WSU_STATS419_FALL2020/";
source_url( paste0(github.path,"master/functions/libraries.R") );
source_url( paste0(github.path,"master/functions/functions-imdb.R") );
```

# Matrix

Create the "rotate matrix" functions as described in lectures.  Apply to the example "myMatrix".

```{r, mychunk-matrix-include}

source_url( paste0(github.path,"master/functions/functions-matrix.R") );

myMatrix = matrix ( c (
                      1, 0, 2,
                      0, 3, 0,
                      4, 0, 5
                      ), nrow = 3, byrow = T);
myMatrix
```

## Transpose Matrix
```{r, mychunk-matrix-transpose}

transposeMatrix = function(matrix) {
  t(matrix);
}

transMatrix = transposeMatrix(myMatrix);
transMatrix
```

## Rotate Matrix
```{r, mychunk-matrix-rotate}

rotateMatrix = function(matrix, clockwise = T) {
  if (clockwise) {
    t(apply(matrix, 2, rev));
  }
  else {
    apply(t(matrix), 2, rev);
  }  
}

rotMatrix = rotateMatrix(myMatrix);
rotMatrix
```

## Rotate Matrix 90 Degrees
```{r, mychunk-matrix-rotate90}

rotateMatrix90= function(matrix, clockwise = T) {
  rotateMatrix(matrix, clockwise);
}

rot90Matrix = rotateMatrix90(myMatrix)
rot90Matrix
```

## Rotate Matrix 180 Degrees
```{r, mychunk-matrix-rotate180}

rotateMatrix180= function(matrix, clockwise = T) {
  rotateMatrix(
    rotateMatrix(
      matrix));
}

rot180Matrix = rotateMatrix180(myMatrix)
rot180Matrix
```

## Rotate Matrix 270 Degrees
```{r, mychunk-matrix-rotate270}

rotateMatrix270= function(matrix, clockwise = T) {
  rotateMatrix(
    rotateMatrix(
      rotateMatrix(
        matrix)));
}

rot270Matrix = rotateMatrix270(myMatrix)
rot270Matrix
```


